### ISSUE TITLE
"Reuse available numbers" not working correctly when opening multiple containers at once

### ISSUE THREAD

**Issue by MadClown** [stoically/temporary-containers#105] opened 2018-03-23 04:57 UTC
- Temporary Containers Version: 0.77
- Firefox Version: 59.0.1
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: Multi-Account Containers 6.0.0

### Actual behavior
'Open All in Tabs' in bookmark folders opens bookmarks in the same container.

### Expected behavior
Each bookmark with a different domain opens in its own container.

### Steps to reproduce

1. Bookmark three or more websites in the same folder. I used five bookmarks when I tested because it was easier to reproduce this when there's more bookmarks.
2. Use 'open all in tabs' to open the bookmarks.

### Notes
It's not guaranteed that all will open in the same container. As an example, when testing 5 bookmarks, two loaded in container 6 and the other three loaded in container 7. On another occasion, four loaded in the same container while only one website loaded in a separate container. All were different domains.

**Comment by stoically** [comment] 2018-03-23 13:03
Hi, thanks for the report. Unfortunately I'm not able to reproduce this. With fresh profile und just Automatic Mode enabled (or even every domain configured to "Always per Website"), it opens every website in its own Temporary Container when clicking "Open All in Tabs".

To further track down the problem a debug log would be really helpful:

- Open a new tab and navigate to "about:debugging"
- Tick the "Enable debugging" checkbox (untick again when you're done posting the Issue)
- Scroll down to Temporary Containers and click the "Debug" link
- Confirm the dialog with OK, you now see "Developer Tools" with "Console" selected
- Type into the console "log.DEBUG=true" (without the quotes), it should respond with "true" (type "log.DEBUG=false" into the console when you're done posting the Issue)
- Now reproduce your issue
- Switch back to the "Developer Tools", select everything in the console
- Copy everything in the console, paste it into a .txt file, save the file, and attach it to the issue by drag&drop'ing it into the text-box

**Comment by MadClown** [comment] 2018-03-23 16:34
Sorry, I should have done more testing. Can you test it with 'reuse available number' since I noticed it only happens when I have this enabled.  The websites open in the same container number, but if they were actually the same container, wouldn't they be the same color as well (I have random color enabled)? Also, MAC treats them as a different containers because there will be multiple entries of the same number with different color. 

When using 'keep counting' enabled, everything works fine.

**Comment by stoically** [comment] 2018-03-23 17:11
That I can confirm, thanks for the additional information. It's just the number not correctly being assigned, but in fact it's different containers under the hood - as you correctly spotted by checking the MAC list. Will look into a fix.

**Comment by crssi** [comment] 2018-05-09 11:31
In that case not only the numbers, but also the color is not correctly being assigned.

Cheers

**Comment by stoically** [comment] 2019-03-31 14:34
Fixed in version 0.92. Let me know if something still doesn't work as expected.

**Closed by stoically** 2019-03-31 14:34 UTC
Labels: bug
