### ISSUE TITLE
Focus/Cursor not working in Firefox 67 beta

### ISSUE THREAD

**Issue by BryanQuigley** [stoically/temporary-containers#224] opened 2019-03-21 06:11 UTC
- Temporary Containers Version: 0.91
- Firefox Version: 67.0b3-1 (snap 193)
- Operating System + Version: Ubuntu 19.04 Dev 
- Non-default Options/Preferences in Temporary Containers: Automatic on.

### Expected behavior
In Firefox 66:
1. Install https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/
2. Enable Automatic mode
3. Ctrl - T for new tab, note how you immediately have focus/cursor in the new tab and can type.

### Actual behavior
Upgrade to Firefox 67 beta 
..
3. Ctrl - T for new tab, note how you can't immediately type and have to click on the new tab.

### Notes
I previously had a similar (but worse) issue tracked in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1489876
That was resolved, and so far this one only seems to impact Temporary Containers add-on.  Never did figure out what fixed it so could be related.

**Comment by stoically** [comment] 2019-03-21 10:16
Did you try with Multi-Account Containers and opening a new container tab from their popup? TC just uses the tabs.create API for WebExtensions and sets the active parameter - there's no API to focus the omnibar. I'm afraid this can't be fixed in an Add-on.

**Comment by BryanQuigley** [comment] 2019-03-21 22:58
Yup, Multi-Account Containers still works.

I'm happy to report to bugzilla (is that what makes sense?) but this time I can only reproduce it against this one add-on.

**Comment by stoically** [comment] 2019-03-22 12:24
Did some debugging and in turns out that in Firefox Beta 67.0b3 and Firefox Nightly 68.0a1 (2019-03-22) the [`tabs.onCreated`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onCreated) event fires with the [`active`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#Type) property set to `false` for Ctrl+T and clicking the new tab icon. TC relies on the correct `active` value being set, since it hands it down to `tabs.create`. I'd consider this a serious regression and would advise reporting it to Bugzilla.

**Comment by BryanQuigley** [comment] 2019-03-22 22:21
Thanks for the debugging analysis.  Reported https://bugzilla.mozilla.org/show_bug.cgi?id=1538378

**Comment by stoically** [comment] 2019-03-22 22:57
Thanks for reporting. Maybe consider changing the bug title to something more accurate like `tabs.onCreated fires with active set to false for new tabs`.

**Comment by BryanQuigley** [comment] 2019-03-22 22:58
updated with recommendation

**Comment by stoically** [comment] 2019-03-25 18:25
Closing since it's not a TC issue.

**Closed by stoically** 2019-03-25 18:25 UTC
Labels: firefox bug
