### ISSUE TITLE
All temporary containers lost on session restore

### ISSUE THREAD

**Issue by dverbru** [stoically/temporary-containers#266] opened 2019-06-07 09:37 UTC
- Temporary Containers Version: 0.98
- Firefox Version: 67.0 64-bit (it also happened with previous Firefox versions)
- Operating System + Version: Ubuntu 18.04
- Non-default Options/Preferences in Temporary Containers: _Delete no longer needed Temporary Containers_ set to 5 minutes instead of 15. Perhaps more non-default preferences, I am not sure.

### Actual behavior
Often on the next restart after Firefox didn't terminate normally (like a system crash), when recovering the previous session all temporary containers are lost. In other words, all tabs that were in temporary containers are now loaded in the default container, **dangerously breaking all isolation at once without warning**. Tabs in normal non-temporary containers are restored properly.

### Expected behavior
Tabs are always restored in the same temporary container they were on the previous session.

### Notes
I usually have between 100 and 200 tabs open, most of them in temporary containers.

**Comment by sbr61** [comment] 2019-06-07 11:22
Did you specify _Always open in this container_ for your permanent containers (maybe that is the reason why they are restored properly)? Can you try the _Automatic mode_ (under _General_ in the TC options)? This should cause other tabs to be restored in (new) temporary containers on session restore.

**Comment by dverbru** [comment] 2019-06-07 14:33
Yes, I did specify _Always open in this container_ for some sites. That's actually the reason I have permanent containers in the first place: for sites I visit often and I want to stay logged in. Yet, many of the tabs that were correctly restored in permanent containers are for domains without such container preference set, that's why I think this issue only affects temporary containers.
I tried _Automatic mode_ a couple of times, I like the idea but it doesn't work for me, mainly because of Google services that I use in the default container. And even then, that would be a workaround for this issue and it will still affect people with default preferences.

**Comment by stoically** [comment] 2019-06-08 08:48
The only workaround currently is to click the restore button in under 10seconds, which would prevent the container cleanup on startup, until I get around to implement a real fix, as outlined in #263. Closing as duplicate.

**Closed by stoically** 2019-06-08 08:48 UTC

**Comment by dverbru** [comment] 2019-06-08 09:54
Ah, thanks for the tip, I'll try to be faster next time! :D

Sorry for the duplicate ticket, I searched for similar open bugs, but since #263 is currently labelled as “enhancement” I didn't find it.

**Comment by stoically** [comment] 2019-06-08 09:58
You're welcome, just check how lucky luke does it. ;)

No problem - technically it's not a bug but a missing feature. I've marked #263 as bug anyway.
