### ISSUE TITLE
Opening a new tab of the same container should have same behaviour as the normal new tab.

### ISSUE THREAD

**Issue by enko** [stoically/temporary-containers#369] opened 2020-02-12 07:56 UTC
- Temporary Containers Version: 1.7
- Firefox Version: 74.0a1 (2020-02-08) (64-Bit)

### Actual behavior

Use the keyboard shortcut for opening a new tab from the same container as the current container. The new tab will be next to the current tab.

See this video:

![uhfq5-nsjmi](https://user-images.githubusercontent.com/19407/74313927-e1ea5f80-4d74-11ea-85c4-13963a5cb185.gif)

### Expected behavior

I would expect the new tab to be at the end of the tab list, like when I'm pressing `ctrl+t`.

### Steps to reproduce

Select a tab that it not at the end and press the shortcut to open a new tab of the current container.

**Comment by crssi** [comment] 2020-02-12 09:47
Is it a bug or this is simply controled by pref `browser.tabs.insertAfterCurrent`
Can you go into `about:config` and check the value of `browser.tabs.insertAfterCurrent`?

**Comment by stoically** [comment] 2020-02-12 09:59
It's a bug in the category of [`why did you even do that`](https://github.com/stoically/temporary-containers/blob/2f18a6cfb762a89c50b9ba2c86de683293152a22/src/background/tabs.ts#L295).

`browser.tabs.insertAfterCurrent` is a good hint, with the bug fixed one can control the behavior to their liking with that.

**Comment by crssi** [comment] 2020-02-12 10:05
But... here (FF v73, Win10) I cannot reproduce, but I can control with `browser.tabs.insertAfterCurrent`... that is why I am confused.

**Comment by stoically** [comment] 2020-02-12 10:08
It's about the keyboard shortcut <kbd>Alt</kbd>+<kbd>X</kbd>.

**Comment by crssi** [comment] 2020-02-12 10:16
But OP is saying

> when I'm pressing ctrl+t

Here is my video of ctrl+t behavior: https://www.dropbox.com/s/sw2mcgq2b4l0ane/newtab.mp4?dl=0

**Comment by stoically** [comment] 2020-02-12 10:17
OP is expecting <kbd>Alt</kbd>+<kbd>X</kbd> to behave the same way as <kbd>Ctrl</kbd>+<kbd>T</kbd>.

**Comment by stoically** [comment] 2020-02-21 09:39
Fixed in just published v1.8

**Closed by stoically** 2020-02-21 09:39 UTC
Labels: bug
