### ISSUE TITLE
Initializing failed in Firefox 77.0

### ISSUE THREAD

**Issue by quample** [stoically/temporary-containers#414] opened 2020-06-03 00:57 UTC
Just updated Firefox (on Win 10 1909) to version 77.0 released on June 2, 2020 and the add-on encountered an error.
This also caused errors in the [Firefox multi-account container add-on](https://github.com/mozilla/multi-account-containers#readme) and [Firefox Facebook container add-on](https://github.com/mozilla/multi-account-containers#readme)

the exact output is given below:

Error: An unexpected error occurred

Restarting Firefox with add-ons disabled and then syncing Firefox using the Firefox account reinstalled all add-ons and now every add-on works without any issues.

**Comment by rhymefororange** [comment] 2020-06-03 10:10
Same for me. Among these things, gmail tab opened in a container stopped working and just shows a blank page.
I don't have a Firefox account and don't plan to get one. Any suggestions how can I fix this without using a Firefox account?

**Comment by rhymefororange** [comment] 2020-06-03 10:21
I followed the debug log wiki page and here is my log sample. It is a merge of 2 exports (after Firefox started and after I reloaded the Temporaty Containers add-on.
Maybe some messages are not related to this add-on, but still hope this would be useful.
[console-export.log](https://github.com/stoically/temporary-containers/files/4722609/console-export.log)

**Comment by gitthehubs** [comment] 2020-06-03 11:23
Same problem here since the Firefox 77 update, firefox multi-account-containers does not work correctly and temporary containers giving an error and did not load correctly. The problem seems to be in the firefox multi-account-containers add-on and not in the temporary containers add-on.

I added my solution to the firefox multi-account-containers add-on gituhub issues page.
https://github.com/mozilla/multi-account-containers/issues/1759
Copy/paste my solution:

I solved the problem as it is caused by an about:config setting in Firefox. In my user.js I had the line:
user_pref("network.file.disable_unc_paths", true);
Delete or comment out this line in the user.js and edit your about:config to delete the preference. Restart your Firefox browser and it should work again.

**Comment by rhymefororange** [comment] 2020-06-03 13:39
Just deleting `network.file.disable_unc_paths` parameter in `about:config` seems to fix it. At least it worked for me and Firefox Multi-Account Containers and Temporary Containers are working as previously.

**Comment by stoically** [comment] 2020-06-03 14:10
Yeah, seems like `disable_unc_paths` is the cause. Related issue: https://github.com/ghacksuserjs/ghacks-user.js/issues/923

**Comment by rikkit** [comment] 2020-06-05 11:48
I don't have either a `user.js` or `network.file.disable_unc_paths` in `about:config`, and containers doesn't work (shows a blank arrow) - any ideas anyone? Sorry for the support request.

Some other extensions of mine have also broken (LastPass, uBlock, ZenHub) and for some reason `twitter.com` won't load. I'm going to try a profile refresh later but thought I'd log something here in case it's relevant.

**Comment by Radagast** [comment] 2020-06-07 13:51
This was an issue on Nightly a couple of months but it was fixed and I've been running with  ```network.file.disable_unc_paths``` set true since then. 

Just tried 77 and everything works as it should until I add the pref and set true. then it's the same issue I had on Nightly.

Bugs:

[here](https://bugzilla.mozilla.org/show_bug.cgi?id=1536796) 

[here](https://bugzilla.mozilla.org/show_bug.cgi?id=1634267)

I believe the milestone is 78.

**Comment by rhymefororange** [comment] 2020-07-22 22:41
Since we are on 78 now, I added `network.file.disable_unc_paths` back in `about:config` and set it to `true`. I restarted Firefox and FF Multi Account Containers as well as Temporary Containers are working fine for me.
So I think we can close this issue if I didn't miss anything.

**Comment by stoically** [comment] 2020-07-22 23:49
Sounds good, thanks for checking

**Closed by stoically** 2020-07-22 23:49 UTC
Labels: incompatible firefox-pref
