### ISSUE TITLE
"View Page Source" problem

### ISSUE THREAD

**Issue by rampaa** [stoically/temporary-containers#321] opened 2019-11-07 22:04 UTC
- Temporary Containers Version: 1.3
- Firefox Version: 70.0.1 64-bit
- Operating System + Version: Windows 10
- Non-default Options/Preferences in Temporary Containers:
Autamatic mode: Enabled.
Isolatation>Global>Target Domain: Different From Tab Domain & Sub Domains
Instead of creating a new tab replace the current tab in case of isolation: Enabled
Automatically close leftover redirector tabs after 2 seconds: Enabled

### Actual behavior
Clicking "View Page Source" on a local HTML file opens up a new blank tab. 

### Expected behavior
Clicking "View Page Source" should display page source.

### Steps to reproduce
1. Make sure automatic mode is enabled.
2. Open a local HTML file with Firefox. The adress bar should display something like file:///C:/Users/User/Desktop/blabla.html
3. Right click on the page and click "View Page Source"

**Comment by stoically** [comment] 2019-11-08 06:28
TC doesn't interfere with anything that `file:///` tabs are doing, so its probably a problem with your Firefox. Would you mind testing with a new profile? That's easily done on `about:profiles`.

I've tried to reproduce with your env and preferences, and for me the page source of local html files opens up correctly in a new tab in the same temporary container.

**Comment by rampaa** [comment] 2019-11-08 07:24
Tried with a fresh profile but it did not help. Your last sentence, on the other hand, did help me to pinpoint the problem. 

When I open a file with Firefox by double clicking on the file itself, it is not opened in a temporary container at all and the aforementioned problem occurs. But if I manually enter its path to the address bar, then View Page Source works as intended. So I guess the real problem is file not being opened within a temporary container from the get-go.

**Comment by stoically** [comment] 2019-11-08 07:54
Tried by double-clicking, which opens the local html file in no container, clicking "view page source" then correctly opens a new tab with the source for me. Does the tab that opens in your case has `view-source:file:///..` as address?

**Comment by stoically** [comment] 2019-11-08 08:16
Interesting. Normally TC shouldn't reopen the tab in that case, since its not a real request and not a `about:blank/home/newtab` tab, and for me it indeed doesn't happen. Since I unfortunately can't reproduce it on my end, I'd need a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) and a preferences export to debug this further.

**Comment by rampaa** [comment] 2019-11-08 08:27
[log.zip](https://github.com/stoically/temporary-containers/files/3823591/log.zip)

**Comment by stoically** [comment] 2019-11-08 08:36
Thanks. So it's a bug indeed, the problem being that the view page source tab gets in a state that's detected as new tab because of changes introduced in #146 before starting to load `view-source:`.

Relevant line in the log: `"[onUpdated] url changed" {"status":"loading","url":"about:blank"}`

**Comment by stoically** [comment] 2019-11-09 08:01
Fixed in [v1.4beta2](https://github.com/stoically/temporary-containers/releases). Please let me know if something doesn't work as expected.

**Closed by stoically** 2019-11-09 08:01 UTC
Labels: bug
