### ISSUE TITLE
New tab will re-open  as temporary container multiple times

### ISSUE THREAD

**Issue by randomchars42** [stoically/temporary-containers#190] opened 2018-11-04 18:32 UTC
## Set up:

  * Automatic Mode: enabled
  * Global Isolation, Navigating in Tabs should open new Temporary Containers: If the Navigation Target Domain does not match the active Tabs Domain (Subdomains won't get isolated)

## Steps to reproduce:

  * click on a link on a page in default container with target="_blank" (will open in new tab), the target is on a different domain

## Expected behaviour:

  * link-target opens in new temporary container

## Actual behaviour:
 
  * link-target opens in new temporary container _but_ (I'm guessing here)
  * the tab opens as normal tab
  * gets replaced by a temporary container, because Automatic Mode is enabled
  * gets replaced by a temporary container, because it's got a different domain
  * you could extend this if the loaded domain has a per-domain rule to always open in a new container

## Question:

 * is there a way to avoid re-opening a tab multiple times?
 * if my guesses are correct: is there a way to detect when a tab matches the first rule, open a new temp. container and stop there?

**Comment by stoically** [comment] 2019-02-07 18:36
There's already [a test](https://github.com/stoically/temporary-containers/blob/16e61cc813f076f44fec569b7a686d790f2b7cd0/test/background.isolation.test.js#L283-L295) for that. For some reason redirects cause this. Can you confirm that in your case redirection takes place (this could be http -> https)? If not, a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) would be really helpful.

**Comment by randomchars42** [comment] 2019-02-08 04:34
I've tested it. And  it seems it happens as well when I try to open a link to a location with https.
Attached is a debug log.
first call to a site which then gets redirected to https
second call (line ~3956) to a site with https as link target
Hope it helps?

**Comment by kelbyers** [comment] 2019-03-30 17:46
I'm seeing the same thing when I use Temporary Containers with Automatic Mode along with Google Containers. When I click on a result link from a google search, the new tab gets opened twice, with each result in a separate container.

I have tried playing around with the isolation settings, and can get it to open one tab in no container and one tab in a temporary container, but that is all I have been able to get it to do. If I have automatic isolation disabled, then only one tab will open, and it will either be in the default container, or in one assigned by Multi-Account Containers.

Alternatively, if I disable Google Containers, and use Multi-Account Containers, then only one tab is opened from a result, in a new temporary container.
[temp_container_debug.txt](https://github.com/stoically/temporary-containers/files/3025769/temp_container_debug.txt)

**Comment by stoically** [comment] 2019-03-31 00:41
@randomchars42 Thanks for the log, it helped me to pin the issue down and it'll be fixed in the next version.

@kelbyers That's a different issue. The specific container extensions (forks of Facebook Container) open new tabs if the user tries to navigate in the container to a domain that's not on their list. I've opened #234 to track that.  Though, if you use isolation in TC, using the specific container extensions is redundant.

**Comment by stoically** [comment] 2019-03-31 14:30
Fixed in version 0.92. Let me know if something still doesn't work as expected.

**Closed by stoically** 2019-03-31 14:30 UTC
Labels: bug

**Comment by stoically** [comment] 2019-04-02 18:38
Had to revert the fix since it was causing isolation to not work properly in some redirect scenarios (also added tests for that).

Not sure how to implement the fix, maybe it's not possible at all because of how isolation works:

- Tab open with `http://example.com` loaded
- Click link to `http://notexample.com` (requestId1)
  - Gets isolated because `http://notexample.com !== http://example.com`
  - requestId1 is marked canceled
- `http://notexample.com` redirects to `https://notexample.com` (requestId1)
  - gets canceled
- `http://notexample.com` opens in new tab (requestId2)
- `http://notexample.com` redirects to `https://notexample.com` (requestId2)
  - Gets isolated because `https://notexample.com !== http://example.com` (compares against the original opener)
  - requestId2 is marked canceled
- `https://notexample.com` opens in new tab (requestId3)

Oh well, after writing it down I realized that it might be possible to keep track of redirects (requests with the same requestId) and compare to the last seen url for a requestId instead of the original opener tab.

**Comment by stoically** [comment] 2019-04-03 10:48
Added the fix again with said redirect tracking, available in version 0.95.

**Comment by grenzor** [comment] 2019-04-07 18:40
@stoically

I'm facing a bug which I think is related to the above. Where if I'm logged into an account in a container and I middle click a link then the link open in a new tab in the same container but it will not be logged in to the account, somehow all cookies/storage don't work or get deleted. This doesn't happen every time I middle click a link but it does happen rather frequently. Didn't face this issue in versions <0.91 but did experience it on 0.92 and 0.95.

**Comment by stoically** [comment] 2019-04-07 19:06
@grenzor TC doesn't delete any storage unless the TC itself gets removed; so in your case it's probably actually a new container and you just think it's the same container, because the number might be wrongly assigned due to the new way how container numbers are determined (#105), which also was introduced recently. Do you have the reuse numbers preference activated? On top of that, it could also have something to do with the fix implemented here, which might isolate new tabs when it's supposed to not isolate. I'd need a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) to see what's actually going on though (optimally in a new issue).

**Comment by grenzor** [comment] 2019-04-07 19:20
The container was a manually created container with a single name (the container still exists and not deleted). I don't have reuse numbers activated. I am using MAC as well if that matters. I do think it has to do something to do with the redirect isolation fix but I'm not 100% sure. I can make a new issue if you think it's needed.

**Comment by stoically** [comment] 2019-04-07 20:09
If this affects a permanent container (and no TC isolation takes place), then TC doesn't interfere at all, since you stay in that permanent container, and thus storage should be unchanged. In this case you would have to report to Bugzilla.

**Comment by grenzor** [comment] 2019-04-07 20:32
Ok, will do. Just a last question, is there no chance the redirect isolation fix here or some problem with using MAC+TC automatic mode that is causing this? I swear I noticed this behavior start with 0.92. Would me testing whether I get this issue with 0.91 be useful at all or is there just no way TC could be the cause here?

**Comment by stoically** [comment] 2019-04-07 20:46
Since your new tab opens in the same permanent container, there's no way TC does anything to the storage - since the only thing TC does *when* removing storage is calling `contextualIdenties.remove`, and in this case you couldn't open a tab in that permanent container anymore. Even if TC would somehow do some sort of isolation inbetween, you end up in your permanent container in the end (as per your description of the issue), and there your storage should be intact (unless maybe some other Add-on tampers with it).
