### ISSUE TITLE
Site Causes Infinite Tab/Containers to Open

### ISSUE THREAD

**Issue by roanutil** [stoically/temporary-containers#130] opened 2018-04-16 04:17 UTC
- Temporary Containers Version: .87
- Firefox Version: 59.0.2
- Operating System + Version: MacOS 10.13.4
- Non-default Options/Preferences in Temporary Containers: Automatic mode, Random color/icon, Global Always, Multi-Account Containers Enabled
- Other installed Add-ons + Version: 1Password 4.7.0.90, Cisco WebEx 1.0.14, Diable WebRTC 1.0.20, HTTPS Everywhere 2018.4.11, Privacy Badger 2018.4.10, uBlock Origin 1.15.24

### Actual behavior
..New Container/Tab for macrumors.com and new containers/tabs will continue to open indefinitely. Not the only site to exhibit this issue. But the only one I made note of.
### Expected behavior
..Only one new container/tab for macrumors.com

### Steps to reproduce

1. ..Launch FireFox
2. ..left click in URL bar
3. ..type macrumors.com
4. ..hit return key

### Notes
..

**Comment by nzstefinitely** [comment] 2018-04-16 04:25
Yeah, seeing the same kind of behaviour here: https://github.com/stoically/temporary-containers/issues/129

**Comment by roanutil** [comment] 2018-04-16 15:50
@nzstefinitely it does seem similar. I created a separate issue because that is supposedly specific to Facebook and use of the Facebook Containers add-on. 

As I am not using Facebook Containers and the issue does not involve Facebook I felt that it is likely an unrelated bug.

**Comment by nzstefinitely** [comment] 2018-04-16 20:51
@roanutil yeah that's fair. #129 appears to be a duplicate of #125 in any case. 

Out of interest, I'm assuming that you have Facebook Multi-Account Containers installed. Do you have MacRumors set to always open in a certain MAC container?

**Comment by roanutil** [comment] 2018-04-16 21:03
@nzstefinitely No I don't have Facebook or Multi-Account Container add-ons installed.

No, I don't have any permanent containers setup. Although.... I may have set it previously... I wonder if those settings persist after uninstalling the Multi-Account Container add-on....

**Comment by nzstefinitely** [comment] 2018-04-16 21:07
@roanutil is there any reason to have the Temporary Containers 'Multi-Account Containers' option enabled if you don't have MAC installed or any permanent containers setup? Would be curious to see whether turning that off has any impact on your issue here. 

Don't know anything for sure here, just guessing.

**Comment by roanutil** [comment] 2018-04-17 02:41
@nzstefinitely I had still had that enabled from when I had MAC installed. Disabled it and the problem persists.

**Comment by stoically** [comment] 2018-04-30 11:53
This seems to be a specific problem with the `Always` Isolation configuration, doesn't happen with `does not (exactly) match`

**Comment by sixpointzero** [comment] 2018-05-10 19:56
I can confirm this behaviour on [BBC](https://www.bbc.com/capital/story/20180508-young-chinese-are-sick-of-working-overtime) as well. The page doesn't load and the number of containers keeps on increasing in the same tab. This happens with Temporary Containers 0.89 and Firefox 59.0.2.

**Comment by TiagoTiago** [comment] 2018-09-10 16:41
I've had this issue when opening i.redd.it and v.redd.it links while on Reddit

**Comment by bitstreamout** [comment] 2018-11-12 13:05
Also have trouble with Containeraise together with Temporary Containers ... e.g. have the pattern heise.de within News container ... now open hesie.de which cause open temp1 container, then Containeraise move this to News Containers, Temporary Containers open a new tmp2, then Containeraise ... ,  Temporary Containers open tmp<n> with <n> = unlimited.  Is there anyway that Temporary Containers repects other addons?

**Comment by stoically** [comment] 2019-01-22 20:17
I can't reproduce this issue anymore in the latest TC version 0.90. Let me know if it is still a problem.

@bitstreamout The combination with containerise is another issue. You can follow progress in #177

**Closed by stoically** 2019-01-22 20:17 UTC
Labels: bug

**Comment by yorky35** [comment] 2019-02-06 00:33
I still get this behaviour on https://www.bbc.co.uk/news. Does not happen if Containerise is disabled.

**Comment by mjsielerjr** [comment] 2019-04-14 21:20
I receive this issue when trying to log into a university website. The website opens a new tab to authenticate the session, then enters the infinite loop.

**Comment by stoically** [comment] 2019-04-15 06:34
@yorky35 The bug with containerise is fixed, see #177.

@mjsielerjr Could you provide steps to reproduce (which site, what to click), a list of other installed add-ons that might interfere and/or ideally a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log)? Without that information I'm unfortunately unable to look into it.

**Comment by mjsielerjr** [comment] 2019-04-19 15:48
> @mjsielerjr Could you provide steps to reproduce (which site, what to click), a list of other installed add-ons that might interfere and/or ideally a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log)? Without that information I'm unfortunately unable to look into it.

Thanks for the quick response. I think I fixed it doing some domain isolation tweaks.

**Comment by mjsielerjr** [comment] 2019-04-19 17:06
@stoically 

I reinstalled both Firefox Multi-Account Conatiners and Temporary Containers. I think my problem was enabling the "open new tab in a new container if it doesn't match the subdomain" for "Navigating in Tabs should open new Temporary Containers". I disabled that and now I can log in successfully.

**Comment by stoically** [comment] 2019-04-19 17:14
Glad you figured it out.

Login-breakage (new TC when redirection happens) is to be expected when using Navigating in Tabs Isolation - though, it's possible to unbreak by overwriting the isolation using per domain isolation with excluding of target domains.  But an infinite loop should definitely never happen, so if it's a public site let me know so I can look into an actual fix.

**Comment by mjsielerjr** [comment] 2019-04-19 17:24
@stoically 

Unfortunately, it's not a public domain. It's a school website that's used to upload class documents, etc. 

The infinite loop was caused, I think, by using Firefox Multi-Acccount Containers in conjunction with Temp containers being created when a new tab with a different subdomain being opened. What happened was I had saved the school website as a container called "school", then when I logged in, it would open a new tab using a different URL to verify that the login information was correct, but because the new tab was a new tmp container it didn't have the information anymore, then it would revert to the school container. The school container would then repeat the process of opening a new tab to verify that the information contained in school was valid, and it would keep repeating itself. 

But like I said, I was able to get around this using the above settings. 

I also tried to overwrite the isolation using per domain isolation excluding target domains, but I wasn't successful at setting the correct parameters. I eventually ran out of time and just gave up, re-installed, etc.

**Comment by stoically** [comment] 2019-04-19 17:46
If it's the site itself repeating the login-redirection process, then that's unfortunately nothing that can get fixed in TC.

It should be just `school.tld` as per domain pattern and `login.redirection.tld` as excluded target pattern (all other preferences can be kept on default). Though, if there's some "hidden" redirection with yet another domain going on, it'd need checking the developer tools network tab to find all domains that need to get excluded. A dedicated logger would be nice (#228).
