### ISSUE TITLE
Make automatic mode open a temporary container only if I'm in default container

### ISSUE THREAD

**Issue by spastorino** [stoically/temporary-containers#98] opened 2018-03-18 02:03 UTC
If I go an open a permanent container where I use a specific gmail account I don't want automatic mode to interfere with it.

**Comment by stoically** [comment] 2018-03-18 14:58
Automatic Mode doesn't interfere with regular loading of websites in permanent containers. Though, I just realized that if you try to load a website in a permanent container that is assigned to "Always open in" in another permanent container with Multi-Account Containers, then you only get to choose between a temporary container and the assigned permanent container - not the permanent container you originally wanted to load the site in. That should not be the case, but it should indeed let you choose the original container you wanted to load the website in. If that's not your use-case, then please let me know what exactly you experience, how to reproduce it and if you maybe have other preferences configured.

Another solution would be if it'd be possible to assign multiple containers, and with that also be able to choose from multiple containers (maybe even including a temporary one): https://github.com/mozilla/multi-account-containers/issues/849

**Comment by spastorino** [comment] 2018-03-19 00:04
That's exactly what's happening to me and this https://github.com/mozilla/multi-account-containers/issues/849 if implemented is great.

Not sure if you need more info.

**Comment by stoically** [comment] 2018-03-21 11:45
Just published version 0.77 with the enhancement. Let me know if something isn't working as expected.

**Comment by spastorino** [comment] 2018-03-21 13:45
@stoically solution is perfect meanwhile https://github.com/mozilla/multi-account-containers/issues/849 is implemented.

**Comment by spastorino** [comment] 2018-03-22 01:02
@stoically there's still an issue that's happening in one gmail account that's not the one used by default which uses two factor authentication. After the first question being correct and letting me open the right container, I get redirected see ...

![screenshot from 2018-03-21 21-59-23](https://user-images.githubusercontent.com/52642/37745417-7895344e-2d53-11e8-81a4-7aa74ed179eb.png)

And I'm back in the same issue.

**Comment by spastorino** [comment] 2018-03-22 01:08
BTW, I think it's not related with two factor auth. When I said it worked was because I was already logged in in the corresponding container but if you're not you get a redirect and suggest Tmpxxx container instead of the right one

**Comment by stoically** [comment] 2018-03-22 11:02
@spastorino Could you maybe provide some steps on how to reproduce (maybe even including a debug log)? I'm unfortunately not able to reproduce it myself.

**Comment by spastorino** [comment] 2018-03-22 13:20
Ok, sorry for not being clear and thanks for your help and work :).

Let me try to explain better ...
I have a personal gmail account which I'm logged in, in a container called `Gmail Personal`. The url I visit is https://mail.google.com/mail/ and the option `Always open in Gmail Personal` is activated for this url. Then I have another work email under `Gmail WyeWorks` container using the same url.
What I want is to open `Gmail WyeWorks` container and use my work email.

To reproduce the issue ...
1) Logout gmail on `Gmail WyeWorks` container
2) Open a tab on `Gmail WyeWorks` container
3) https://mail.google.com/mail/
4) It ask to open in `Gmail WyeWorks` or `Gmail Personal`, choose `Gmail WyeWorks`
5) Fill name and password and try to log in
6) You will be redirected and in that part is where you will see ...
![screenshot from 2018-03-21 21-59-23](https://user-images.githubusercontent.com/52642/37745417-7895344e-2d53-11e8-81a4-7aa74ed179eb.png)
And you will need to open in `Gmail WyeWorks` again instead of `Gmail Personal` or a tmp container.

I think the issue is more general, in a situation like the one described in this issue, when you're redirected the plugin is losing track of where the container was firstly opened. I guess you would like to respect in what container was firstly opened the tab for all the session I'd say. Otherwise, when there's a redirect to https://mail.google.com/mail/ with some params in the url you will hit again the same issue.

Hope what I wrote helps, otherwise I will try to clarify more. Do you need a debug log?. Where does the plugin store that?.

**Comment by stoically** [comment] 2018-03-22 13:42
No problem and thanks for the additional informations. Unfortunately I'm still not able to reproduce the issue. If I select the not-assigned container on the confirm page I can login without further interruptions.

So in this case a debug log would be really helpful to track down the problem:

- Open a new tab and navigate to "about:debugging"
- Tick the "Enable debugging" checkbox (untick again when you're done posting the Issue)
- Scroll down to Temporary Containers and click the "Debug" link
- Confirm the dialog with OK, you now see "Developer Tools" with "Console" selected
- Type into the console "log.DEBUG=true" (without the quotes), it should respond with "true" (type "log.DEBUG=false" into the console when you're done posting the Issue)
- Now reproduce your issue
- Switch back to the "Developer Tools", select everything in the console
- Copy everything in the console, paste it into a .txt file, save the file, and attach it to the comment by drag&drop'ing it into the text-box

**Comment by spastorino** [comment] 2018-03-22 15:44
Ok, I know what the issue is about. I can send you the debug log if you're interested but anyway, the thing is ...

First, just in case I didn't mention, I've enabled Isolation -> Multi Account Containers
Then, in my case I'm being redirected to log in at some point to https://accounts.google.com and https://accounts.google.com.uy
In order to fix the issue I should put both on Always open in Gmail Personal, otherwise, due to Isolation -> Multi Account Containers they will both be opened in Tmp containers.
I've added https://accounts.google.com to Always open in Gmail Personal, the thing is https://accounts.google.com.uy only redirects to https://accounts.google.com and I can't using the UI add also that address so I keep hitting this issue. Was looking to do so using the config files, still looking ...

**Comment by stoically** [comment] 2018-03-22 16:02
Glad you figured out the actual issue. A rather hacky way to get the .uy domain on the "Always open in" list is to temporarly set `network.http.redirection-limit` in about:config to `0`

Possible actual solutions:
* Separate configurations available directly in Multi-Account Containers https://github.com/mozilla/multi-account-containers/issues/473
* Additional configurable list of Domains per Container that are not isolated if the MAC Isolation is enabled

**Closed by stoically** 2018-03-22 16:02 UTC
Labels: enhancement

**Comment by stoically** [comment] 2018-03-22 16:17
Ah, yeah, that's indeed the only solution in this case, since you probably don't want to assign the .uy domain to only the "WyeWorks" container. I'll look into implementing #104
