### ISSUE TITLE
Automactic mode does not work well with "Limit to Designated Sites" option Multi-Account Containers extension

### ISSUE THREAD

**Issue by blis5fool** [stoically/temporary-containers#443] opened 2020-07-17 21:42 UTC
- Temporary Containers Version: 1.8
- Firefox Multi-Account Containers Version: 7.0.2
- Firefox Version: 78.0.2 (64-bit)

### Actual behavior
Temporary Container is set to Automatic mode.
Link opened in new tab from a Multi-Account Container that is limited to a certain domain opens in a default container.

### Expected behavior
Links should open in a temporary container. I also use "Automatically create "Deletes History Temporary Containers" instead of normal Temporary Containers" option, and the new tab fails to open in a "Deletes History Temporary Containers" as well.

### Steps to reproduce

Pre-requisite:
- "Firefox Multi-Account Containers" extension installed

Steps:
1. Browse to "https://slickdeals.net/"
2. Set this site to always re-open in a container
3. Go to  "Manage Containers".
4. Select the container and check "Limit to Designated Sites"
5. Click a [deal](https://slickdeals.net/f/14201510-shimano-ultegra-11-speed-chain-30-and-cassette-67-72-at-rei?src=frontpage&attrsrc=Test%3AjfyYieldOptimize%3Atest-scenario-1-jfy%7CFeature%3AisPersonalized%3Afalse) on SlickDeals site
6. Click "See Deals" button or other links in the description.

**Comment by blis5fool** [comment] 2020-07-17 21:52
Can also replicate with reddit. Create a container for reddit then limit it to just that site.
I guess Facebook container is special because I don't have to check that option and the links opens outside of the container. But, it opens properly in temporary container.

**Comment by stoically** [comment] 2020-07-17 22:33
Looks like a duplicate of #439

**Comment by blis5fool** [comment] 2020-07-18 01:14
> 
> 
> Sounds like a duplicate of #439

Indeed it is.

**Closed** 2020-08-06 06:29 UTC
