### ISSUE TITLE
Spawns tabs endlessly together with Containerise v3.1.0

### ISSUE THREAD

**Issue by pezz** [stoically/temporary-containers#287] opened 2019-07-09 00:24 UTC
- Temporary Containers Version: 1.0
- Firefox Version: 67.0.4
- Operating System + Version: Arch Linux
- Non-default Options/Preferences in Temporary Containers: Lots?
- Other installed Add-ons + Version: Multi-Account Containers, Containerise, Cookie Auto Delete

Noticed some strange behaviour by Firefox and saw that this addon updated.

This simply doesn't work as it used to. Any time a temp container is created a new tab is opened with the URL it and not in the temp container.

With automatic mode on this is especially bad as new tabs keep getting opened indefinitely.

Turning off automatic mode fixes the unlimited new tabs opening, but even without it nothing seems to open in a new temp container now.

**Comment by Radagast** [comment] 2019-07-09 01:01
@pezz 
Are you using Containerise? 

I'm not completely sure where the problem is yet but the latter also had an update today and for me, reverting back to 3.0.1 fixed the issues with multiple tabs opening. TC is working correctly with Automatic mode on.

**Comment by pezz** [comment] 2019-07-09 01:05
Ah, you are correct - Containerise was also updated, disabling it stops this from happening.

Might see about logging a bug there, cheers.

**Comment by crssi** [comment] 2019-07-09 07:21
https://github.com/kintesh/containerise/issues/70#issuecomment-509492949

**Comment by stoically** [comment] 2019-07-09 09:39
Opened https://github.com/kintesh/containerise/pull/74 over at Containerise to hopefully get a fix in soon. The only thing I could do in TC is completely disable Automatic Mode + Isolation if that Containerise version is detected.

Reopening for visibility.

**Comment by TiagoTiago** [comment] 2019-07-09 17:11
It's not the first time this addon has been involved in an infinite tab-opening bug; maybe it might be a good idea to add a check for having opened new tabs with the same URL too  many times in a row in the last few seconds, and then just replace the URL with one pointing to an error message suggesting an workaround with a link to try to open the URL anyway?

**Comment by stoically** [comment] 2019-07-09 18:13
Yeah, I agree that having a fail-safe would be good for incompatibilities of this kind. Maybe I get around to implement one this time (and don't forget [it](https://github.com/stoically/temporary-containers/issues/88#issuecomment-371721114) again).

**Comment by stoically** [comment] 2019-07-09 18:43
FYI, Containerise is planning to revert the change causing this issue: https://github.com/kintesh/containerise/issues/70#issuecomment-509736333

**Comment by stoically** [comment] 2019-07-09 20:20
Fixed in Containerise v3.2.0

**Closed by stoically** 2019-07-09 20:20 UTC
Labels: incompatible add-on

**Comment by notDavid** [comment] 2022-03-03 13:07
Fyi for people stumbling upon this;

i'm seeing the same issue (endless tabs spawning in Firefox 97) which seems to be caused in combination with the https://github.com/bekh6ex/firefox-container-proxy extension. It happens when visiting https://translate.google.com/

No idea why, i don't have any specific container settings for that website...

(Temporary Containers v1.9.2)
