### ISSUE TITLE
Considerations for not ignoring Facebook Container

### ISSUE THREAD

**Issue by kyounger** [stoically/temporary-containers#367] opened 2020-02-05 20:05 UTC
Not submitting the template, because I think this is more of a discussion.

I noticed that the the Facebook Container is ignored by design. This does cause me one issue, though, as any links clicked on in that container are opened up in the Default container. I have sort of come to expect that any link that tries to open in my browser will never end up opening in the Default Container, and I can be assured of isolation.

Would there be a way to make the two extensions play better together so that links that are clicked on that are not from the facebook domains get opened into a temporary container? I'm very willing to take that up with the Facebook Container repo (maybe even put together a PR) if you can suggest a design that would work.

Thanks for the awesome extension; it changed how I used web browsers!

**Comment by stoically** [comment] 2020-02-06 08:36
Didn't realize that websites opened from FBC and similar end up in the default container (with automatic mode and/or isolation enabled, I suppose). Actually I would consider this a bug. Currently it checks whether a tab [was opened from FBC](https://github.com/stoically/temporary-containers/blob/c7a6d071fe5339b67363ce9ac9b1f918cb50cab8/src/background/request.ts#L482), and if that's the case, it [completely ignores the request](https://github.com/stoically/temporary-containers/blob/c7a6d071fe5339b67363ce9ac9b1f918cb50cab8/src/background/request.ts#L183-L184). The reason for that, IIRC, was to prevent tab duplication. Not sure exactly, but I think it should be enough to use the openerTab url check only to remove eventually left-over tabs instead (similar to the [redirector tabs](https://github.com/stoically/temporary-containers/blob/7451cc549dca6b57bf519884a70b1078282d8002/src/background/tabs.ts#L220) logic).

Happy you like the extension!

**Comment by stoically** [comment] 2020-02-20 18:11
Was looking into fixing this, but couldn't reproduce it, and also realized that only the initial request gets ignored, which is captured by FC and reopened into the default container - at which point TC reopens, if Automatic Mode is active. So to look into this I'd need steps to reproduce and/or a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log).

**Comment by stoically** [comment] 2020-07-04 12:50
Closing since I can't act on missing STR. If someone can provide STR, please do so.

**Closed by stoically** 2020-07-04 12:50 UTC
Labels: cannot reproduce
