### ISSUE TITLE
Multi Account Isolation + Facebook Containers issue

### ISSUE THREAD

**Issue by nzstefinitely** [stoically/temporary-containers#129] opened 2018-04-16 03:59 UTC
- Temporary Containers Version: 0.87
- Firefox Version: 59.02
- Operating System + Version: MacOS 10.13.3
- Non-default Options/Preferences in Temporary Containers: Multi-Account Containers Isolation enabled
- Other installed Add-ons + Version: 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/19705220/38789293-7d721aec-418d-11e8-9ae7-818c46d4d02e.png">

### Actual behavior
Facebook Container extension + Temporary Containers extension seems to conflict. When trying to open facebook.com in a new tab, both extensions fight each other creating an infinite loop of Temporary Containers. 

### Expected behavior
Any domains not assigned to an existing container, open in a temporary container. 

### Steps to reproduce
1. Install and enable Facebook Container
3. Install and enable Multi-Account Containers
4. Install and enable Temporary Containers
5. Enable 'Multi-Account Isolation' in Temporary Containers
6. Open a new default tab and enter facebook.com
7. Watch hell break loose.

### Notes
[debugging.txt](https://github.com/stoically/temporary-containers/files/1913827/debugging.txt)
And here's what ends up happening to MAC: 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/19705220/38789539-01b82764-418f-11e8-9763-9420db053c2f.png">

**Comment by nzstefinitely** [comment] 2018-04-16 04:03
Note: this happens with or without 'Automatic Mode' enabled

**Comment by nzstefinitely** [comment] 2018-04-16 04:05
Note 2: with isolation disabled, but automatic mode enabled, this loop starts but seems to stop after three instances. That is, I'm left with three containers having been created and three facebook tabs open.

**Comment by listalltabs** [comment] 2018-04-16 12:39
Hi! Is this perhaps a dupe of #125?

**Comment by nzstefinitely** [comment] 2018-04-16 20:45
@listalltabs yes it appears to be, thanks!

**Comment by stoically** [comment] 2018-04-30 11:49
Released a new TC Version today informing users about the upcoming requirement of the `management` permission, which will be needed to have a way to automatically prevent such errors from happening in the future.

**Comment by stoically** [comment] 2018-05-16 12:56
Published fix with version 0.90

**Closed by stoically** 2018-05-16 12:56 UTC
Labels: incompatible add-on
