### ISSUE TITLE
DDG videos circumvent Left Mouse Isolation

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#379] opened 2020-02-25 09:38 UTC
FF 73.0.1, Windows 10
TC 1.8

Additional to default settings:
General -> Automatic Mode: Check
Isolation -> Global -> Mouse Click -> Left Mouse: Choose anything except `Never`

Open `duckduckgo.com`.
Search for `whatever video`.
Click on any video in the video section.

Expected behavior: link opens only in a new tab/container
Actual behavior: link opens in the same tab/container and in a new tab/container

Cheers

**Comment by stoically** [comment] 2020-02-25 10:49
Can reproduce. Debug log would be helpful for this one.

**Comment by crssi** [comment] 2020-02-25 11:40
I am not sure I understood.
You can reproduce or you can't reproduce?
If you can reproduce, do you need my debug logs?

**Comment by stoically** [comment] 2020-02-25 11:41
I can, but don't have the time to look into it currently, so when I get the time, already having a debug log would help :)

**Comment by crssi** [comment] 2020-02-25 11:42
I see. Sure, will try to provide one today.

Cheers and thank you

**Comment by crssi** [comment] 2020-02-25 13:07
[379.log](https://github.com/stoically/temporary-containers/files/4250095/379.log)

**Comment by stoically** [comment] 2020-06-10 11:26
While looking into this I found that DDG sends the request to the video again after the first request was correctly canceled by TC. I'm not sure how this could be sanely handled by TC, since it's probably some weird JavaScript magic doing this. Best solution probably would be if TC allowed to define a rule like "if originating from DDG always isolate" - which is something that would be possible with #397.

**Comment by stoically** [comment] 2020-07-04 12:51
Closing since the issue itself can't be solved by TC.

**Closed by stoically** 2020-07-04 12:51 UTC
Labels: incompatible website
