### ISSUE TITLE
"Automatic mode" does not honor global setting "If the Navigation Target Domain does not match the active Tabs Domain (Subdomains won't get isolated)"

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#137] opened 2018-05-01 06:14 UTC
- Temporary Containers Version: 0.89
- Firefox Version: 59.0.3
- Operating System + Version: Windows 10

### Actual behavior
Opening several external links to the same domain opens every page in separate containers.

### Expected behavior
Opening first one should open a page in a new container only if there are no other containers targeted to same domain/subdomain, otherwise it should open in the already used container for that domain/subdomain.

**Comment by stoically** [comment] 2018-05-09 09:57
I'm assuming you're opening the external links all from the same (different) source domain? In this case it is expected behavior that every Isolation opens a new Temporary Container, since each time the currently active Tabs Domain is compared to the target external Domain. I'm closing this in favor of #141 since I feel the Issues are related. Feel free to let me know if I'm mistaken.

**Closed by stoically** 2018-05-09 09:57 UTC

**Comment by stoically** [comment] 2018-05-09 12:44
You could e.g. set GitHub to "Always open in" in that Container using Multi-Account Containers (described on the Temporary Containers AMO page). That would help with external links and already open and logged in tabs.

Or you could define a exception Per Domain Isolation rule for GitHub, that would help with already open and logged in tabs, but not with external links.

Hope that helps.

**Comment by crssi** [comment] 2018-05-09 13:42
I know... I have tried both, but its not only github... everyday some other domain arises.
I still believe it be more practical out of the box without the need of additional addon and would be zero config.
Couldn't you treat external link invocation as the same source when using Automatic mode?

**Comment by crssi** [comment] 2018-05-09 13:44
Or add a checkbox under Automatic mode, to achieve this. Pretty please :smile: 

Anyway, whatever you decide... thank you for great addon.

**Comment by stoically** [comment] 2018-05-09 14:01
That's unfortunately not really possible, since it would require to tell Firefox that external links should open in an already open Tab. I can't imagine a workaround either, since there's no way to distinguish between *really external* links and e.g. opening bookmarks or directly navigating to a site. This would lead to all sorts of problems, so I'm afraid I can't help with that.

**Comment by crssi** [comment] 2018-05-12 07:17
Hmmm, just curious...
How does this work then when defined by for example with "Firefox Multi-Account Containers"?
Does the "special" container with domain preset have to be created up front before and cannot be created in real-time?

I hope you understand what I am asking... written so weird :smile:. If not understandable, just let me know and will try to explain differently.

Cheers
