### ISSUE TITLE
Sometimes the opening tab is opened in a container that is should not be

### ISSUE THREAD

**Issue by crssi** [stoically/temporary-containers#141] opened 2018-05-08 14:52 UTC
- Temporary Containers Version:
- Firefox Version: 0.89
- Operating System + Version: Win 10
- Non-default Options/Preferences in Temporary Containers:
Isolation -> Global -> middle mouse = If the clicked Link Domain does not match the active Tabs Domain (Subdomains won't get isolated)

### Actual behavior
Double-clicking multiple links, linked to unique domains different than source page, one by one opens new tabs in new containers.
Sometimes new tab/container is opened is the same container than it is the source page.
Sometimes more tan one new tab is opened in the same new container.

### Expected behavior
Every new tab should be opened in the new container, when sub/domain is different.

It does not happen every time, but quite often to easily reproduce.

### Reproduce steps
Go to comment `https://github.com/ghacksuserjs/ghacks-user.js/issues/172#issuecomment-387608582` and middle-click all for links... every link should open in a new tab but in the same container... instead every link is opened is the new tab and new container.

**Comment by stoically** [comment] 2018-05-09 09:53
> Sometimes more tan one new tab is opened in the same new container.

Do you by chance have the "Reuse available numbers" preference active? If so this could be the same Issue as #105. If not, I'd need a way to reproduce this, or optimally a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) (with description what should happen instead), since the steps to reproduce you provided work correctly for me. In fact, 

> instead every link is opened is the new tab and new container.

this is expected behavior, since every click compares `github.com` against `mozilla.org` and thus a new Temporary Container is created.

**Comment by stoically** [comment] 2018-05-09 12:45
Ok, then I'm closing this in favour of #105. Thanks for reporting.

**Closed by stoically** 2018-05-09 12:45 UTC
Labels: cannot reproduce, more info needed

**Comment by crssi** [comment] 2018-05-13 12:11
I am now using TC v0.90beta1 and I can still reproduce upper problem every time.
With keeping or reusing numbers is the same result.
