### ISSUE TITLE
Automatic mode does not intercept links from external apps

### ISSUE THREAD

**Issue by roothorick** [stoically/temporary-containers#442] opened 2020-07-16 15:39 UTC
- Temporary Containers Version: 1.8
- Firefox Version: 78.0.2

### Actual behavior
Links from external apps are always opened in no container.

### Expected behavior
Each link from an external app should generate and be opened in a new temporary container.

### Steps to reproduce
1. Enable automatic mode
2. Click on a link in an external app

### Notes
New profiles are not affected. I cut the enabled extensions down to 4 (MAC, TC, uBO and uMatrix) to no effect. Installed the same 4 extensions in the new profile and it did not impact functionality. Restarting Firefox after changing the setting does not appear to have an effect.

[support.txt](https://github.com/stoically/temporary-containers/files/4932425/support.txt)

[temporary_containers_preferences_2020-7-16_10.37.30.json.txt](https://github.com/stoically/temporary-containers/files/4932510/temporary_containers_preferences_2020-7-16_10.37.30.json.txt)

Unable to get any debug log output (related: #441)

**Comment by roothorick** [comment] 2020-07-16 16:59
I was able to get a debug log. Lines with names or URLs of unrelated tabs have been removed for privacy.
[console-export-2020-7-16_11-45-30.txt](https://github.com/stoically/temporary-containers/files/4932959/console-export-2020-7-16_11-45-30.txt)

**Comment by stoically** [comment] 2020-07-17 09:02
So this only happens in a specific profile, even with all other Add-ons disabled?

**Comment by stoically** [comment] 2020-07-17 16:34
Thanks for providing the debug log, it says

```
"[webRequestOnBeforeRequest] handling request failed" "TypeError: this.pref.isolation.domain is not iterable"
```

And indeed, in your preference export isolation.domain is an object and not an array. So it seems that something went wrong while upgrading from an older version. Could you try the fixed preferences:

[temporary_containers_preferences_2020-7-16_10.37.30.json.txt](https://github.com/stoically/temporary-containers/files/4938958/temporary_containers_preferences_2020-7-16_10.37.30.json.txt)

**Comment by roothorick** [comment] 2020-07-17 17:12
Yep, that did fix it.

I wonder what upgrade broke it...

**Comment by stoically** [comment] 2020-07-17 18:35
The migration from object to array happened from 0.103 to 1.0, so already a while ago. Maybe something in the Firefox JS engine changed which made it problematic or something.

But since this seems to be resolved, I'm going ahead and close this issue.

**Closed by stoically** 2020-07-17 18:35 UTC

**Comment by humCopper** [comment] 2020-12-10 04:47
I was able to reproduce the issue with a new profile with Temporary Containers as the only add-on
Firefox: 83.0
Temporary Containers: 1.9.1

[console-export-2020-12-9_22-45-12.txt](https://github.com/stoically/temporary-containers/files/5670303/console-export-2020-12-9_22-45-12.txt)
