### ISSUE TITLE
Should cookies be listed in Managed Data?

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/temporary-containers#211] opened 2019-02-23 21:27 UTC
When using TC, should cookies be listed in Firefox's Managed Data interface?

For example, if you load site A in a temporary container A, then load site B in temporary container B, and then open Firefox's Options UI, and click on **Manage Data...** (in the Privacy and Security tab) in temporary container C, should cookies from site A and site B be listed?

If so, is there a way to tell what cookies are available in a specific container (and only that container)?

**Comment by crssi** [comment] 2019-02-24 11:57
FF can show the cookies, but container cannot access cookies in the other containers or non-container area, also non-container site cannot access other containers.
Take the [Cookie Quick Manager](https://addons.mozilla.org/firefox/addon/cookie-quick-manager/) extension which will also show you in which container the specific cookies live.

Is this the answer to your question?

**Comment by Gitoffthelawn** [comment] 2019-02-24 19:46
@crssi Yes, it does.  And thank you for the recommendation for the other extension.

Here's what I now understand.  Please let me know if I've got it correct.

- Container A can see cookies in Container A.  It cannot see cookies in Container B.  It cannot see cookies that are not in any container.
- Container B can see cookies in Container B.  It cannot see cookies in Container A.  It cannot see cookies that are not in any container.
- Firefox's **Manage Data...** UI will always show cookies in containers A and B, as well as cookies that are not in any container.

**Comment by crssi** [comment] 2019-02-25 09:41
AFAIK that is correct. To be really sure, we should wait for @stoically to confirm.

You can also add to the upper list the web extensions which have appropriate permissions.

Cheers

**Comment by Gitoffthelawn** [comment] 2019-02-25 22:42
@cssri Thanks again.  I've added web extensions below (hopefully I got it right):

* Container A can see cookies in Container A.  It cannot see cookies in Container B.  It cannot see cookies that are not in any container.

* Container B can see cookies in Container B.  It cannot see cookies in Container A.  It cannot see cookies that are not in any container.

* Firefox's **Manage Data...** UI will always show cookies in containers A and B, as well as cookies that are not in any container.

* Web Extensions with cookies permissions can see all cookies in containers A and B, as well as cookies that are not in any container.

**Comment by Gitoffthelawn** [comment] 2019-02-25 23:57
@stoically Whenever you have a chance (no rush), can you confirm the above?

BTW, I noticed that once a temporary container is closed, Firefox's **Manage Data...** can still view all the cookies from that container.  This is true even after waiting for the duration of what is specified in "Delete no longer needed temporary containers".  Is this the desired behavior?

**Comment by crssi** [comment] 2019-02-26 10:08
For some reasons **Manage Data...** is not refreshed in a real-time... maybe a bug or feature.
Close **Manage Data...**, **reload Options** page and reopen **Manage Data...**... are cookies still shown?
If yes, try to close Options page and reopen again.

Some cookies will still be there... they can come from persistent containers and some are from some extensions... for example uBO filter lists can leave cookies or amp.cloudflare.com from WE [Redirect AMP to HTML](https://addons.mozilla.org/firefox/addon/amp2html/) Those are totally harmless.
But cookies from closed temporary containers after duration time specified in "Delete no longer needed temporary containers" **must vanish**.

Can you confirm that?

Cheers

**Comment by Gitoffthelawn** [comment] 2019-02-27 22:05
@crssi Thanks.  I originally wrote the word "cookies".  I meant to write "storage items".  I must have been hungry. ;)

I've updated the post above, and confirmed the behavior.

Should storage items be available from closed containers, even after waiting the duration specified in "Delete no longer needed temporary containers"?

Can new containers access that data?

**Comment by crssi** [comment] 2019-02-28 08:02
I don't have "Storage items" column, did you mean "Storage" column under "Manage data..."?
Firefox -> Options -> Privacy & Security -> Cookies and Site Data -> Manage data... button?

**Comment by stoically** [comment] 2019-03-01 15:17
@Gitoffthelawn To my knowledge it's correct what you described in https://github.com/stoically/temporary-containers/issues/211#issuecomment-467214163

> Should storage items be available from closed containers, even after waiting the duration specified in "Delete no longer needed temporary containers"?

Yes, they should be removed as well.

> Can new containers access that data?

If orphaned data from temporary containers for whatever reason remain on disk, new TCs will not be able to access that data because of the [container-separation](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers).

**Comment by stoically** [comment] 2019-03-10 12:08
Closing as this seems to be resolved. Let me know if you find steps to reproduce for orphaned container data and I'd be happy to open a Firefox Bugzilla ticket.

**Closed by stoically** 2019-03-10 12:08 UTC
