### ISSUE TITLE
Allow the new tab to always open in a specific container

### ISSUE THREAD

**Issue by ghost** [stoically/temporary-containers#410] opened 2020-05-19 08:37 UTC
Right now there is no way to make the new tab always open in a specific container AFAIK.

**Comment by crssi** [comment] 2020-05-19 11:49
Just out of curiosity: Why would you do that or why do you need to do that?

**Comment by SeBarosanul** [comment] 2020-05-20 08:04
Searx doesn't work well if the new tab isn't in the same container.

**Comment by crssi** [comment] 2020-05-20 08:12
Can you be more specific with some steps to reproduce, so someone can replicate the problem to help you.
Which searx (url) or do you mean provider?
If provider, which one, how to install...

**Comment by SeBarosanul** [comment] 2020-05-20 08:32
Go to searx.tuxcloud.net, make a dedicated container for it and make some changes in preferences so you have a cookie in that container. Add it as a search engine and set it as default. Now, when you try to search, no matter the advanced automated mode setting, you will just go to the searx.tuxcloud.net website and have to type your search again, but that doesn't happen if the new tab is opened in the searx dedicated container.

**Comment by crssi** [comment] 2020-05-20 08:52
Try to install extension [New Tab Override](https://addons.mozilla.org/firefox/addon/new-tab-override/) and set `https://searx.tuxcloud.net/` as default new tab url.

**Comment by stoically** [comment] 2020-05-23 10:02
If the searx.tuxcloud.net search engine works based on POST queries and between searching and landing on the page the container gets switched, then it won't work. In that case you'd need to use GET queries instead.

**Comment by r-a-y** [comment] 2020-05-24 21:18
I've run into this problem before with POST queries and Searx.

@SeBarosanul - You can either use the [Cookies feature](https://github.com/stoically/temporary-containers/wiki/Advanced#cookies) of Temporary Containers, so you can keep using your custom settings with Searx. Or use another extension to inject the cookies into the HTTP header like Header Editor or HTTP Header Mangler.

**Comment by GitGangGuy** [comment] 2020-05-28 10:42
@stoically I'm running into the same problem.
I'm using DuckDuckGo with POST-over-GET (from the privacy settings) so that my search queries can't be traced back through my history (there are other advantages to this as well).
I've used the "Add custom search engine" add-on to create a custom search method from the firefox url bar that uses post when opening duckduckgo for search.
However, now temporary containers comes into play and breaks my idea. Since new tabs are opened in a new temporary container, but duckduckgo lives in my personal permanent container, my post request will be intercepted and I just land on the ddg homepage. 
@crssi I've already tried the "New Tab Homepage" extension to open ddg automatically in a new tab, but this comes with its downsides as well. For example, I won't be able to search through my history from the auto-focused duckduckgo search bar. Also, every time I open a new tab ddg gets pinged, which isn't really private either. Lastly, after already having over 40 extensions enabled, opening firefox's new tab is faster than loading duckduckgo's website.
@r-a-y I'm not sure if I can apply this in my case...

**Comment by stoically** [comment] 2020-05-28 11:12
The only workaround that comes to mind when POST is required, is to open the new tab directly with the correct container when wanting to use DDG. Something that could assist with that is [Easy Container Shortcuts](https://addons.mozilla.org/firefox/addon/easy-container-shortcuts/) - and the next version of Multi-Account Containers gets shortcuts as well.

**Comment by r-a-y** [comment] 2020-05-28 22:26
@GitGangGuy - I use DuckDuckGo as a secondary search engine using POST queries (via the "Add custom search engine" addon or via Mycroft) and I'm able to use it successfully with Temporary Containers. One thing though is you need to make sure that your new tab is using "Firefox Home" under about:preferences.

The cookie technique I mentioned above doesn't seem to work with DDG unfortunately.

**Comment by stoically** [comment] 2020-05-29 05:22
@r-a-y It works if you stay in the same container, but the mentioned issues arise when a permanent container is assigned and with that the container switches while searching (same behavior as new tab "blank page"). Cookies for DDG should work tho, if it doesn't that'd be a different issue

**Comment by GitGangGuy** [comment] 2020-06-15 18:14
I believe that since the new tab is a privileged environment it’s rather difficult to implement such functionality, but it would be great to see progress on something to prevent losing POST data on a container switch.

**Comment by stoically** [comment] 2020-06-15 20:59
Something hacky that might work: when a POST request from an about:newtab or about:home tab is detected, instead of directly reopening the URL into a new tab, first open an [extension page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages) with a form that, submit that using JS and then change the request headers using [onBeforeSendHeaders](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders)

**Comment by stoically** [comment] 2020-07-04 12:53
Closing as this seems to be resolved. The enhancement asked in the issue itself might become possible with #397.

**Closed by stoically** 2020-07-04 12:53 UTC
