### ISSUE TITLE
Tabs set to load/reload at timed intervals in different Firefox window causes new TCs to open in current window

### ISSUE THREAD

**Issue by noto10** [stoically/temporary-containers#389] opened 2020-03-18 06:01 UTC
Use case: 

A few Firefox windows are open. In one of the background windows, an extension is used to load or reload new or existing predetermined tabs at different intervals. TC is set to global isolation. Upon timed load/reload, the new instances of the predetermined tabs are loaded in the current window. 

This is rather disruptive. Is there anyway to avoid it?

I'm not sure if this is related to https://github.com/stoically/temporary-containers/issues/347

**Comment by stoically** [comment] 2020-03-18 07:37
I'd need some steps to reproduce (which site, which add-on to reload) and/or ideally a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) to help with that, because in theory it shouldn't happen.

**Comment by stoically** [comment] 2020-04-27 08:55
Closing in favor of #400

**Closed by stoically** 2020-04-27 08:55 UTC
Labels: cannot reproduce
