### ISSUE TITLE
Tabs Opened in Wrong Window (After Minimize?)

### ISSUE THREAD

**Issue by rue** [stoically/temporary-containers#284] opened 2019-07-07 10:19 UTC
- Temporary Containers Version: 0.103
- Firefox Version: 67.04
- Operating System + Version: macOS 10.14
- Non-default Options/Preferences in Temporary Containers:
 ** MAC open in new if not same domain: enabled
 ** isolation options, but this happens regardless of whether it's a special domain or generic
- Other installed Add-ons + Version:
1Password extension (desktop app required)
Bloody Vikings!	0.9.4
CanvasBlocker	0.5.12
Clear Flash Cookies	1.0.1
Cookie AutoDelete	3.0.2
Decentraleyes	2.0.12
Don't touch my tabs! (rel=noopener)	2.1.1
Firefox Multi-Account Containers	6.1.0
hotfix-update-xpi-intermediate	1.0.6
HTTPS Everywhere	2019.6.27
Location Guard	2.2.0
Startpage.com — Private Search Engine	1.1.4
Temporary Containers	0.103
uBlock Origin	1.18.6
User-Agent Switcher	1.2.18

### Actual behavior
Pressing Cmd-T to open a new window sometimes opens that tab _in another window_ (the one I was previously in, as far as I can tell). I think this only happens in windows that have just been un-minimized. Repeating Cmd-T keeps opening tabs in the other window.

Going to the other window, *closing the opened tabs there*, and then coming back to the original window, Cmd-T works correctly at least until next minimization.

Disabling `Temporary Containers` prevents this problem. Disabling `Don’t touch my tabs!` doesn’t.

### Expected behavior
Cmd-T always opens a new tab in the current window.

### Steps to reproduce
1. Open new window with Cmd-N
2. Open a couple tabs
3. Minimize window
4. Unminimize window
5. Use Cmd-T to open new tab

**Comment by stoically** [comment] 2019-07-07 11:11
That's interesting, since TC never creates tabs with `windowId` set, so completely relying on Firefox doing the right thing. So it's either a FF bug or an Add-on incompatibility. Could you maybe try with a new FF profile and import your TC preferences and/or provide a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log), since I'm unfortunately unable to reproduce the issue.

**Comment by stoically** [comment] 2019-07-17 10:07
Closing, since there's not much I can do without the requested information. Happy to reopen if you get around to provide them.

**Closed by stoically** 2019-07-17 10:07 UTC
Labels: cannot reproduce
