### ISSUE TITLE
Container numbers start at 6

### ISSUE THREAD

**Issue by Zlewness** [stoically/temporary-containers#191] opened 2018-11-22 22:19 UTC
I'm having a little problem where I've got 'reuse available numbers' set to on but on this specific profile the numbers all start at 6 and count upward as normal. I don't know how to investigate the phantom temporary container tabs 1-5, or how to reset the extension data to fix this.

This does not happen on a fresh profile, only on this one. I've changed the settings: 'Automatic mode', 'random container color', 'reuse available numbers', 'delete after 5 minutes', global 'ctrl left mouse opens tab if the domain does not match the domain'.

Is there a way to play around to find what's causing this, and also to reset everything without nuking other addon data or resetting the profile?

**Comment by Zlewness** [comment] 2018-11-23 13:16
Some progress: I managed to break it further by changing the 'delete after' value and disabling/enabling remote debugging using the dev tools, then deleting the profile created in the folder, then disabling/renabling it again until the numbers started at 11 and then 16. I'm still not sure if it's a conflict with another addon or with the built in browser toolbox.

I also just reset the addon data to fix the issue by deleting the folders in <path to profile>\Storage\default\moz-extension+++<uuid>\ and \moz-extension+++<uuid^userContextId=4294967295>

**Comment by stoically** [comment] 2019-02-07 18:48
This is odd. What TC does when determining the reused container number is looking at the currently active temporary containers (stored in the browser storage) and picking a free number. The only case I can imagine where you could end up with your issue is if TCs are not deleted properly which would be a serious bug. Do you by chance use Multi-Account Containers or another container Add-on which still listed the containers 1-5? Could you provide a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) if you encounter the issue again? There's also not an easy way of editing the storage to fix this on the fly since it would interfere with how TC works under the hood.

**Comment by Thorin-Oakenpants** [comment] 2019-02-08 08:41
@stoically without doing a massive search to re-find where I read it (it was a moz dev on bugzilla) .. those numbers 1-5 are reserved. 4 of them for the default four containers (personal, work, banking, shopping) and I can't remember the other one (I have an idea it has something to do with PB Mode, which seems weird as PB Mode cannot use containers - maybe it was built in for future development)

I'll see if I can dig up the relevant source

**Comment by Thorin-Oakenpants** [comment] 2019-02-08 09:28
I'm not very good at reading this stuff...

[Here](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/contextualidentity/ContextualIdentityService.jsm#67) starting at line 67 are the five default containers numbered 1 to 5 with no. 5 being public:false

and [here](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/contextualidentity/ContextualIdentityService.jsm#169) on line 169
>  Compute the last used context id (**excluding the reserved userContextIds**

**Comment by stoically** [comment] 2019-02-08 10:14
@Thorin-Oakenpants Thanks for digging into it, but TC doesn't take already existing containers into account when determining the temporary container number - so that's not the problem here.

**Comment by Thorin-Oakenpants** [comment] 2019-02-08 11:27
Yeah .. soz, not my area :) Just seems so relevant that 1-5 is reserved

**Comment by lwvxoxvwl** [comment] 2019-03-16 21:36
I can confirm  that I have the same issue - at first TC would start always at no 6 and now, after few attempts to stop it, every time it start with no 16.

**Comment by stoically** [comment] 2019-03-31 14:33
Probably fixed in version 0.92. Let me know if something still doesn't work as expected (and a [debug log](https://github.com/stoically/temporary-containers/wiki/Debug-Log) would be great in that case).

**Closed by stoically** 2019-03-31 14:33 UTC
Labels: bug
