### ISSUE TITLE
[feature] tab right-click menu options

### ISSUE THREAD

**Issue by mkeroppi** [stoically/temporary-containers#360] opened 2020-01-16 03:56 UTC
I would like to ask for tab right-click menu options, including opening the tab in a temporary container.

**Comment by stoically** [comment] 2020-01-17 19:07
> including opening the tab in a temporary container.

Do you mean re-opening the right-clicked tab in a temporary container? If so, this would be a duplicate of #342

**Comment by mkeroppi** [comment] 2020-01-17 19:33
> 
> 
> > including opening the tab in a temporary container.
> 
> Do you mean re-opening the right-clicked tab in a temporary container? If so, this would be a duplicate of #342

I mean when you "right-click" a tab (on the tab bar), there are various options (including reload tab, close tab, etc.).  I think an option to open the tab in a temporary container would be a convenient user-interface option.

**Comment by stoically** [comment] 2020-01-17 19:38
Right, I'd agree. That's a duplicate of #342 tho, please follow progress there. The issue refers to the "Open tab URL in new temporary container"-action in the popup, which opens the current tab in a new temporary container (you can activate the popup in the preferences in the general section by ticking the popup checkbox, and access the action by clicking the menu button top left and navigating to "actions").

**Closed by stoically** 2020-01-17 19:38 UTC

**Comment by mkeroppi** [comment] 2020-01-17 19:58
> 
> 
> Right, I'd agree. That's a duplicate of #342 tho, please follow progress there. The issue refers to the "Open tab URL in new temporary container"-action in the popup, which opens the current tab in a new temporary container (you can activate the popup in the preferences in the general section by ticking the popup checkbox, and access the action by clicking the menu button top left and navigating to "actions").

I'm not sure if it's the same thing.  That issue talks about a pop-up action for the context menu, NOT the tab menu (right-click in the bar tar).  If I'm wrong I apologize.

**Comment by stoically** [comment] 2020-01-17 20:01
With "context menu" I actually meant the website and tab bar - but you're right, it wasn't spelled out. I've adjusted the issue description accordingly!
